### ISSUE TITLE
HCL - what is it, what is it used for

### ISSUE THREAD

**Issue by surfmuggle** [surfmuggle/firstrun#10]
AFAICT HCL is used mostly for [terraform](https://github.com/hashicorp/terraform) 

 * based on this issue: [Clarification future of HCL](https://github.com/hashicorp/hcl2/issues/14)

 * and this search [hcl trending](https://github.com/trending/hcl?since=daily)

**Comment by surfmuggle** [comment]
Hi  @cnoelker FYI  i was courious about HCL

**Comment by cnoelker** [comment]
https://t3n.de/news/neue-programmiersprachen-trend-1129522
